/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author User
 */


public class HRManager extends javax.swing.JFrame {

    /**
     * Creates new form HRManager
     */
    Color DefaultColor,clickedColor;
    public HRManager() {
        initComponents();
        
        DefaultColor=new Color(153,153,153);
        clickedColor=new Color(104,83,125);
        
        Hometab.setBackground(DefaultColor);
        sectors .setBackground(DefaultColor); 
          employees.setBackground(DefaultColor);
        Search.setBackground(DefaultColor);
        
        actualHome home = new actualHome();
        jLabel1.removeAll();
        jLabel1.add(home).setVisible(true);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sectors = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Hometab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        employees = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        createAccount = new javax.swing.JLabel();
        employees1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(104, 83, 125));
        jPanel2.setForeground(new java.awt.Color(120, 70, 149));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel2.setText("WELCOME , HR Manager ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, -1));

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        jPanel2.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 110, 40));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 890, 100));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sectors.setBackground(new java.awt.Color(153, 153, 153));
        sectors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sectors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sectorsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sectorsMousePressed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel5.setText("Add sectors & roles");

        javax.swing.GroupLayout sectorsLayout = new javax.swing.GroupLayout(sectors);
        sectors.setLayout(sectorsLayout);
        sectorsLayout.setHorizontalGroup(
            sectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        sectorsLayout.setVerticalGroup(
            sectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(sectors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 40));

        Hometab.setBackground(new java.awt.Color(153, 153, 153));
        Hometab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hometab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HometabMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HometabMousePressed(evt);
            }
        });

        jLabel7.setText("jLabel4");

        jLabel8.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel8.setText("Home");

        javax.swing.GroupLayout HometabLayout = new javax.swing.GroupLayout(Hometab);
        Hometab.setLayout(HometabLayout);
        HometabLayout.setHorizontalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HometabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        HometabLayout.setVerticalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HometabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(Hometab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 40));

        employees.setBackground(new java.awt.Color(153, 153, 153));
        employees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeesMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel9.setText("Add Employees");

        jLabel10.setText("jLabel4");

        javax.swing.GroupLayout employeesLayout = new javax.swing.GroupLayout(employees);
        employees.setLayout(employeesLayout);
        employeesLayout.setHorizontalGroup(
            employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeesLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(42, 42, 42))
        );
        employeesLayout.setVerticalGroup(
            employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeesLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)))
        );

        jPanel4.add(employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

        createAccount.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        createAccount.setForeground(new java.awt.Color(204, 204, 204));
        createAccount.setText("Click here to create new account.");
        createAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountMouseClicked(evt);
            }
        });
        jPanel4.add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        employees1.setBackground(new java.awt.Color(153, 153, 153));
        employees1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employees1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employees1MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel11.setText("Add Employees");

        jLabel12.setText("jLabel4");

        javax.swing.GroupLayout employees1Layout = new javax.swing.GroupLayout(employees1);
        employees1.setLayout(employees1Layout);
        employees1Layout.setHorizontalGroup(
            employees1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employees1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(42, 42, 42))
        );
        employees1Layout.setVerticalGroup(
            employees1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employees1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(employees1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)))
        );

        jPanel4.add(employees1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

        Search.setBackground(new java.awt.Color(153, 153, 153));
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });

        jLabel14.setText("jLabel4");

        jLabel13.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel13.setText("Search Employees");

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 40));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo small 1.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 50));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("The Tech Company");
        jLabel3.setInheritsPopupMenu(false);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 230, 100));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 770, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        setSize(new java.awt.Dimension(1014, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sectorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectorsMouseClicked
         NewRole role = new NewRole();
 jLabel1.removeAll();
 jLabel1.add(role).setVisible(true);
        
    }//GEN-LAST:event_sectorsMouseClicked

    private void HometabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HometabMouseClicked
 actualHome home = new actualHome();
 jLabel1.removeAll();
 jLabel1.add(home).setVisible(true);
        
 
    }//GEN-LAST:event_HometabMouseClicked

    private void employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseClicked
   NewEmp emp=new NewEmp();
 jLabel1.removeAll();
 jLabel1.add(emp).setVisible(true);
 
    }//GEN-LAST:event_employeesMouseClicked

    private void createAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountMouseClicked
       Register rgf =new Register();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose(); 
                      
    }//GEN-LAST:event_createAccountMouseClicked

    private void HometabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HometabMousePressed
           Hometab.setBackground(clickedColor);
        sectors .setBackground(DefaultColor); 
          employees.setBackground(DefaultColor);
           Search.setBackground(DefaultColor);
        
    }//GEN-LAST:event_HometabMousePressed

    private void sectorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectorsMousePressed
       Hometab.setBackground(DefaultColor);
        sectors .setBackground( clickedColor); 
          employees.setBackground(DefaultColor);
           Search.setBackground(DefaultColor);
    }//GEN-LAST:event_sectorsMousePressed

    private void employeesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMousePressed
            Hometab.setBackground(DefaultColor);
        sectors .setBackground(DefaultColor); 
          employees.setBackground(clickedColor);
           Search.setBackground(DefaultColor);
        
    }//GEN-LAST:event_employeesMousePressed

    private void employees1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employees1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employees1MouseClicked

    private void employees1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employees1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_employees1MousePressed

    private void SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMousePressed
        // TODO add your handling code here:
        Hometab.setBackground(DefaultColor);
        sectors .setBackground(DefaultColor); 
          employees.setBackground(DefaultColor);
        Search.setBackground(clickedColor);
    }//GEN-LAST:event_SearchMousePressed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
      home newhome=new home();  // TODO add your handling code here:home newhome=new home();
 jLabel1.removeAll();
 jLabel1.add(newhome).setVisible(true);
 
    }//GEN-LAST:event_SearchMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
new Login().setVisible(true); 
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hometab;
    private javax.swing.JPanel Search;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel createAccount;
    private javax.swing.JPanel employees;
    private javax.swing.JPanel employees1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel sectors;
    // End of variables declaration//GEN-END:variables
}
