/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.roledesig;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import ClassPackage.Designation;

/**
 *
 * @author User
 */
public class NewRole extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewRole
     */
    public NewRole() {
        initComponents();
         initComponents();
         
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDepaName = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        txtDId = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDesigName = new javax.swing.JTextField();
        txtDesigId = new javax.swing.JTextField();
        btnSubmit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1191, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 590, 10));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setText(" Department Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 60, 130, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtDepaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, -1));

        jlabel.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jlabel.setText("Department ID");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtDId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtDId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));

        btnSubmit.setBackground(new java.awt.Color(102, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(204, 204, 204));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 560, 130));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setText("Designation Name");

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setText("Designation ID");

        btnSubmit1.setBackground(new java.awt.Color(102, 102, 102));
        btnSubmit1.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        btnSubmit1.setForeground(new java.awt.Color(204, 204, 204));
        btnSubmit1.setText("Submit");
        btnSubmit1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        btnSubmit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDesigName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtDesigId))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addComponent(btnSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDesigName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtDesigId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 570, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1178, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIdActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
if (txtDepaName.getText().isEmpty()||txtDId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fileds cannot be empty" ,
                    "Add Department", JOptionPane.WARNING_MESSAGE);
}else
       {
           String DepartmentId = txtDId.getText();
            String DepartmentName = txtDepaName.getText();
            
            roledesig newDep =new roledesig(DepartmentId,DepartmentName);
            
            if (newDep.addDepartment()) {
                JOptionPane.showMessageDialog(null,"Department Added successfully" ,
                        "Add a new Department", JOptionPane.INFORMATION_MESSAGE);       
            } else {
JOptionPane.showMessageDialog(null,"Sorry! Something went wrong with the application"
   ,"Add a new Department", JOptionPane.WARNING_MESSAGE);
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
     if (txtDesigId.getText().isEmpty()||txtDesigName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty" ,
                    "Add Designation", JOptionPane.WARNING_MESSAGE);
}else
       {
            String DesignationId = txtDesigId.getText();
            String DesignationName = txtDesigName.getText();
            
            Designation newDes =new Designation(DesignationId,DesignationName);
            
            if (newDes.addDesignation()) {
                JOptionPane.showMessageDialog(null,"Desigation Added successfully" ,
                        "Add a new Designation", JOptionPane.INFORMATION_MESSAGE);       
            } else {
JOptionPane.showMessageDialog(null,"Sorry! Something went wrong with the application"
   ,"Add a new Designation", JOptionPane.WARNING_MESSAGE);
            }
        }     
    }//GEN-LAST:event_btnSubmit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField txtDId;
    private javax.swing.JTextField txtDepaName;
    private javax.swing.JTextField txtDesigId;
    private javax.swing.JTextField txtDesigName;
    // End of variables declaration//GEN-END:variables
}
